config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#index'

  get "services" => "static_pages#services"

  get "contact" => 'static_pages#contact'

  get "career" => 'static_pages#career'
  
  # get "signup" => "users#new"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def services
  end

  def contact
  end

  def career
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def full_title(title = '')
       base_title = "AK-Infotech"
       if(!title.empty?)
          title = title + "." + base_title
        else
            base_title
       end 
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Web@ : Ak-Infotech
  </small>
  <nav>
    <ul>
      <li><%= link_to "Contact-Us",   contact_path %></li>
      <li><%= link_to "Career", career_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">

 <div class="container">
        <%=link_to image_tag("Main_Project_logo.png",size: "130x50", :border => 0)  , root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   root_path %></li>
            <li><%= link_to "Services",   services_path %></li>
            <li><%= link_to "Career",   career_path %></li>
            <li><%= link_to "Contact-Us",   contact_path %></li>
          </ul>
        </nav>
      </div>
      </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 <title><%= full_title(yield(:title)) %> </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render  'layouts/shim'%>
</head>
<body>
<%= render  'layouts/header'%>

       <div class="container">
            <%= yield %>
            <%= render 'layouts/footer'%>
        </div>
</body>
</html>

app/views/static_pages/career.html.erb
<h1>Career</h1>
<title><%=yield(:title)%></title>
<hr>
<br>
<p>
<p><h4>Join Our Journey:</h4><br></p>
<p>Contact us right away if you are an intelligent, creative, energetic and risk taking free
spirit with the analytical rigor, willing to work in a collaborative and non-hierarchical environment based on mutual respect. </p>
<p> If You want to join our team @kindly mail us at : <b>mail@akinfotech.co.in</b></p>


</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact us") %>

<h1>Contact Us</h1>
<title><%= yield(:title) %></title>
<hr>
<p>
  Reach Us at : <b>sales@akinfotech.co.in</b><br><br>

  Corporate Address : <b>AK Infotech, A-202 Cosmo Towers, Mira road (East),Thane - 401107 </b>
</p>

app/views/static_pages/index.html.erb
<% provide(:title, "Index") %>
<title><%=yield(:title)%></title>
  <br>
  <br>
  <br>
<div class="center jumbotron">
  <h3><b>Our Vision</b></h3></h3><br>
  <p>
To be the most <b>preferred partner</b> to our clients, employees and stakeholders for realizing the full potential from their investments in IT.</p><br>

    <h3><b>Mission Statement</b></h3>
    <p>
Deliver extraordinary results by fostering an entrepreneurial environment for exceptional people and clients to thrive.</p>
</div>

app/views/static_pages/services.html.erb
<h1>Services</h1>
<title><%=yield(:title)%></title>
<hr>
<p>
	<h4>AK Infotech offers a wide spectrum of services in the field of IT.</h4>
<p>On the basis of our vast and varied experience, with strong focus on Quality work and Service to the clients, we offer various options to suit everyone's budget.</p>
<p> <h5>Our field of expertise are:</h5></p>
<p>
<b>1. OPEX Optimization</b>- Operation Expenditure Optimization Services enable you to reduce your infrastructure costs and improve performance through infrastructure consolidation, classification and policy improvements, and application optimization. With our Cost Optimization Services, you can align your technology and business objectives to deliver optimum results</p>
<p>
<b>2. Resource Management Services</b>- We understand that finding the right IT skills at the right time can make all the difference to you successfully delivering your project and mitigating any risks. As an experienced IT Services company we fully understand the issues that you face when staffing projects and identifying quality technical resources. We constantly strive to take our services to the next level in order to continue to develop long-term partnerships with both candidates and our growing blue chip customer base.</p>
<p>
<b>3. Corporate Training Services</b>- AK Infotech provides corporate trainings for Oracle, SAP, Siebel and any specific customer training requirements.</p>
<p>
<b>4. IT Outsourcing and Solutions Implementations</b>- We take up and run complete IT operations for small to medium scale solution implementations. We can help to reduce your total cost of project ownership, reduce risk, and maintain control by taking up projects or specific tasks totally.</p>	

</p>

app/views/users/new.html.erb
<%provide(:title,'Sign-Up')%>
<h1>Sign-Up</h1>
<p>This will be the sign up page! </p>